[package]
name = "vid2ascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
terminal_size = "0.2.3"
termion = "2.0.1"
ctrlc = "3.2.4"